version: '3'

services:
  webserver-broker:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl:/etc/ssl
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    depends_on:
      - broker

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: broker
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=helloprint-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PGDATA=/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/pgdata

volumes:
  dumps:

networks:
  default:
    external:
      name: helloprint-network
